services:
  umrs-frontend-dev:
    container_name: umrs-frontend-dev
    image: b216/umrs-frontend:dev
    env_file: .env.example
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/app
    # command: npm run start
