min_version = '2025.3.2'

[tools]
node = "22"
"npm:@devcontainers/cli" = "latest" # 0.73.0
"npm:@nestjs/cli" = "latest" # 11.0.5
"npm:@angular/cli" = "latest" # 19.2.3

[tasks.build]
description = 'Build docker development environment'
run = "docker compose --env-file ./.env.example -f docker-compose.dev.yml build"
dir = "{{cwd}}"
alias = 'd'

[tasks.dev]
description = 'Run docker development environment'
run = "docker compose --env-file ./.env.example -f docker-compose.dev.yml up -d"
dir = "{{cwd}}"
alias = 'd'

[tasks.down]
description = 'Remove docker development containers'
run = "docker compose down"
dir = "{{cwd}}"
alias = 'dd'

[tasks.re]
description = 'Restart docker development containers'
run = "docker compose restart"
dir = "{{cwd}}"
alias = 'r'